name: Deployment
on:
  push:
    branches:
      - master
    tags:
      - v*
jobs:
  buildAndUpload:
    name: Build for production
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: npm i -g yarn
      - run: yarn install
      - run: yarn run build
      - run: zip -r david-bauske-resume.zip build
      - run: echo "$BAUSKE_ORG_DEPLOY_KEY" > id_rsa
      - run: scp -i id_rsa david-bauske-resume.zip deploy-bot@bauske.org:/var/www/resume
